# Files excluded from Jekyll builds
exclude:
- README.md
- Gemfile
- Gemfile.lock
- .gitignore


# Installed Gems
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-sitemap
 # - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-default-layout
  - jemoji



# Gem settings
remote_theme: daviddarnes/alembic@main


# Jekyll settings
sass:
  style: compressed # Style compression




# Site settings
encoding: utf-8 # Make sure the encoding is right
lang: fr # Set the site language
title: "Sev Yoga" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Cours de yoga Vinyasa à Dijon" # Site description and default description, also used in jekyll-seo-tag
url: "https://www.sevyoga.fr" # Site url, also used in jekyll-seo-tag
baseurl: ""
permalink: pretty
repo: "https://github.com/sevyoga/site-sevyoga"
email: "sevyoga7@gmail.com"
#css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference


# 8. Site favicons & manifest icons
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  52: '/assets/logos/logo@52px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'


# 9. Site navigation
navigation_header:
- title: Accueil
  url: /
- title: Cours en ligne
  url: /cours-en-ligne/
- title: Présentation
  url: /presentation/
- title: Horaires et Tarifs
  url: /horaires-tarifs/
- title: Contact
  url: /contact/


social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  facebook: https://www.facebook.com/Sev-Yoga-100599325044171/
  youtube: https://www.youtube.com/channel/UCvyC9prP-MXc3fFcbOBCo3Q
  instagram: https://www.instagram.com/sevclem

